-- SCHEMA: public;
GRANT ALL ON SCHEMA public TO PUBLIC;

GRANT ALL ON SCHEMA public TO postgres;

SET client_encoding = WIN1252;

/* CLIENTES */
DROP TABLE IF EXISTS Customers CASCADE;

DROP TABLE IF EXISTS Countries CASCADE;

DROP TABLE IF EXISTS Cities CASCADE;

DROP TABLE IF EXISTS CityAddress CASCADE;

DROP TABLE IF EXISTS CustomerAddress CASCADE;

/* NEGOCIO */
DROP TABLE IF EXISTS Stores CASCADE;

DROP TABLE IF EXISTS Employees CASCADE;

DROP TABLE IF EXISTS EmployeeAddress CASCADE;

DROP TABLE IF EXISTS Bosses CASCADE;

/* PELICULAS */
DROP TABLE IF EXISTS Movies CASCADE;

DROP TABLE IF EXISTS Categories CASCADE;

DROP TABLE IF EXISTS MovieCategories CASCADE;

DROP TABLE IF EXISTS Actors CASCADE;

DROP TABLE IF EXISTS MovieActors CASCADE;

DROP TABLE IF EXISTS Translates CASCADE;

DROP TABLE IF EXISTS MovieTranslates CASCADE;

/* FACTURAS */
DROP TABLE IF EXISTS Rents CASCADE;

DROP TABLE IF EXISTS Bills CASCADE;